# Generated by Django 5.2.2 on 2025-06-09 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='fecha_hora',
            field=models.DateTimeField(),
        ),
    ]
